//-> 2. 设置 总数18张卡片
var card = [
    "#id-Drink",
    "#id-Jam",
    "#id-pingguo",
    "#id-qingjiao",
    "#id-niunai",
    "#id-mianbao",
    "#id-zhangyu",
    "#id-pangxie",
    "#id-xianyu",
    "#id-qiezi",
    "#id-sanwenyu",
    "#id-xigua",
    "#id-huolongguo",
    "#id-boluo",
    "#id-taozi",
    "#id-xiangjiao",
    "#id-caomei",
    "#id-chelizi",
    "#id-yangtao",
    "#id-baicai",
    // "#id-withdraw",
    // "#id-zengjiatuceng",
    // "#id-A",
    // "#id-bofang",
    "#id-kaixinguo",
    "#id-hetao",
    "#id-xiaweiyiguo",
    "#id-huasheng",
    "#id-bigenguo",
    "#id-songzi",
    "#id-badanmu",
    "#id-yaoguo",
    "#id-danhuangsu",
    "#id-dangao",
    "#id-binggan",
    "#id-buding",
    "#id-tangguo",
    "#id-qiaokeli",
    "#id-hongzao",
    "#id-candou",
    "#id-putaogan",
    "#id-manyuemei",
    "#id-shousi",
    "#id-zhouzi",
    "#id-bingsha",
    "#id-suannai",
    "#id-pisa",
    "#id-haixing",
    "#id-haizhe",
    "#id-tongluoshao",
    "#id-nuomici",
    "#id-kuangquanshui",
    "#id-cha",
    "#id-zhangyuxiaowanzi",
    "#id-chengzhi",
    "#id-hebaodan",
    "#id-bingtanghulu",
    "#id-fengmi",
    "#id-feiyuguantou",
    "#id-shengjian",
    "#id-youtiao",
    "#id-yuzijiang",
    "#id-zhutongfan",
    "#id-doujiang",
    "#id-sanmingzhi",
    "#id-paofu",
    "#id-shanbei",
    "#id-dangaojuan",
    "#id-futejia",
    "#id-huangyou",
    "#id-xiangchang",
    "#id-banji",
    "#id-danta",
    "#id-qingning",
    "#id-lajiao",
    "#id-shizi",
    "#id-mojituo",
    "#id-putaojiu",
    "#id-kouxiangtang",
    "#id-xiangcaobingqilin",
    "#id-jiaozi",
    "#id-tilamisu",
    "#id-huoguo",
    "#id-hongshu",
    "#id-bingkuai",
    "#id-mianhuatang",
    "#id-paobing",
    "#id-meishikafei",
    "#id-mantou",
    "#id-qishui",
    "#id-ganlan",
    "#id-jiroujuan",
    "#id-guodong",
    "#id-kafei",
    "#id-shutiao",
    "#id-zhenzhunaicha",
    "#id-xuegao",
    "#id-nailao",
    "#id-kele",
    "#id-tiantong",
    "#id-hanbao",
    "#id-xiezishousi",
    "#id-baomihua",
    "#id-regou",
    "#id-makalong",
    "#id-tianfuluo",
    "#id-paomian",
    "#id-tiantianquan",
    "#id-shupian",
    "#id-huafubing",
    "#id-bangbangtang",
];

//-> 3. 创建 存储所有数据的数组
var list = {
    box: [],
    left: [],
    right: [],
    res: [],
    lastAll: [],
    lastOne: [],
}
